name: CI/CD

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Run vitest
        uses: docker/bake-action@v4
        with:
          targets: test
          set: |
            test.cache-from=type=gha

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/bake-action@v4
        with:
          targets: dist
          provenance: false
          set: |
            dist.cache-from=type=gha
            dist.cache-to=type=gha,mode=max
      - name: Fix file permissions
        run: chmod -R +rX "dist/"
      - name: Upload dist for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Pages
        uses: actions/deploy-pages@v4
