name: Build

on:
  workflow_call:
    inputs:
      upload:
        description: Upload the dist directory for deployment
        required: false
        default: false
        type: boolean

jobs:
  vite:
    name: Vite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build dist
        uses: docker/bake-action@v4
        with:
          targets: dist
          provenance: false
          set: |
            dist.cache-from=type=gha
            dist.cache-to=type=gha,mode=max
      - name: Fix file permissions
        if: ${{ inputs.upload }}
        run: chmod -R +rX "dist/"
      - name: Upload dist for deployment
        if: ${{ inputs.upload }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"