name: CI/CD

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - '!renovate/*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs:
      - test
    uses: ./.github/workflows/build.yml
    with:
      upload: ${{ github.ref == 'refs/heads/main' }}

  deploy:
    name: Deploy
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Pages
        uses: actions/deploy-pages@v4
