name: Test

on:
  workflow_call:

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v4
        with:
          targets: test
          set: |
            test.cache-from=type=gha